on:
  push:
    branches:
      - develop
name: integration tests
jobs:
  integration-tests:
    name: Integration tests & code coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go: ['1.15']
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: Check out code
        uses: actions/checkout@master
      - name: Get dependencies
        run: go mod download
      - name: Format Test
        run: diff <(gofmt -d ./...) <(echo -n)
      - name: Integration tests
        env:
          DISGORD_TOKEN_INTEGRATION_TEST: ${{ secrets.DISGORD_TOKEN_INTEGRATION_TEST }}
          TEST_GUILD_TYPICAL_ID: ${{ secrets.TEST_GUILD_TYPICAL_ID }}
          TEST_GUILD_TYPICAL_TEXT_GENERAL: ${{ secrets.TEST_GUILD_TYPICAL_TEXT_GENERAL }}
          TEST_GUILD_TYPICAL_VOICE_1: ${{ secrets.TEST_GUILD_TYPICAL_VOICE_1 }}
          TEST_GUILD_TYPICAL_VOICE_2: ${{ secrets.TEST_GUILD_TYPICAL_VOICE_2 }}
          TEST_GUILD_TYPICAL_VOICE_GENERAL: ${{ secrets.TEST_GUILD_TYPICAL_VOICE_GENERAL }}
        run: go test -v -race -tags=integration -coverprofile=coverage-integration.txt -covermode=atomic ./...
      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{secrets.CODECOV_TOKEN}} -B develop -c -F integration -f "./coverage-integration.txt" -Z
  unit-tests:
    name: unit tests & code coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go: ['1.13', '1.14', '1.15']
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: Check out code
        uses: actions/checkout@master
      - name: Get dependencies
        run: go mod download
      - name: Format Test
        run: diff <(gofmt -d ./...) <(echo -n)
      - name: unit tests
        env:
          DISGORD_TOKEN_INTEGRATION_TEST: ${{ secrets.DISGORD_TOKEN_INTEGRATION_TEST }}
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{secrets.CODECOV_TOKEN}} -B develop -c -F unit -f "./coverage.txt" -Z

